### ISSUE TITLE
Register generic query handler in dotnet core

### ISSUE THREAD

**Issue by gamoreli** [maldworth/OnionWebApiStarterKit#1]
Hi, I think this generic query handler approach very interesting, do you know how can I register it with native DI in dotnet core?

**Comment by Dekorg** [comment]
hi, i've checked quite a lot of repos with clean architecture and cqrs with use of mediatr, so i wanted to thank you for making OS this starter kit, i think it is one of the best because of extracted crosscutting concerns. So great job and once again thank you!
